Traceback (most recent call last):
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/janreimann/.local/share/virtualenvs/math452_Spring2022-LV5Uatla/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# write your code for solving probelm 2 in this cell

# You can load CIFAR-10 dataset as follows:
CIFAR10_transform = torchvision.transforms.Compose([torchvision.transforms.ToTensor()])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=CIFAR10_transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=CIFAR10_transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=1, shuffle=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# write your code for solving probelm 2 in this cell[39;00m
[1;32m      2[0m 
[1;32m      3[0m [38;5;66;03m# You can load CIFAR-10 dataset as follows:[39;00m
[0;32m----> 4[0m CIFAR10_transform [38;5;241m=[39m [43mtorchvision[49m[38;5;241m.[39mtransforms[38;5;241m.[39mCompose([torchvision[38;5;241m.[39mtransforms[38;5;241m.[39mToTensor()])
[1;32m      6[0m trainset [38;5;241m=[39m torchvision[38;5;241m.[39mdatasets[38;5;241m.[39mCIFAR10(root[38;5;241m=[39m[38;5;124m'[39m[38;5;124m./data[39m[38;5;124m'[39m, train[38;5;241m=[39m[38;5;28;01mTrue[39;00m, download[38;5;241m=[39m[38;5;28;01mTrue[39;00m, transform[38;5;241m=[39mCIFAR10_transform)
[1;32m      7[0m trainloader [38;5;241m=[39m torch[38;5;241m.[39mutils[38;5;241m.[39mdata[38;5;241m.[39mDataLoader(trainset, batch_size[38;5;241m=[39m[38;5;241m128[39m, shuffle[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[0;31mNameError[0m: name 'torchvision' is not defined
NameError: name 'torchvision' is not defined

